import AsyncStorage from "@react-native-async-storage/async-storage";
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { clearGatewayConfig, loadGatewayConfig, saveGatewayConfig } from "@/lib/erpclaw/config";
import { checkGateway, executeGatewayAction, getCatalog } from "@/lib/erpclaw/gateway";
import type { GatewayCatalog, GatewayConfig } from "@/lib/erpclaw/types";
import { amount, emptyHybridLedger, hybridSummary, makeId, queue, type HybridLedger, type OutboxAction } from "@/lib/hybrid-erp";

const STORAGE_KEY = "erpclaw.hybrid.ledger.v1";
type SyncState = "offline" | "ready" | "syncing" | "error";
type HybridContext = { ledger: HybridLedger; loading: boolean; config: GatewayConfig | null; catalog: GatewayCatalog | null; syncState: SyncState; message: string | null; createCompany: (name: string, currency: string, country: string) => void; addCustomer: (name: string, email?: string) => void; addItem: (sku: string, name: string, quantity: number, unitCost: number) => void; addInvoice: (quantity: number, unitPrice: number) => void; connect: (config: GatewayConfig) => Promise<void>; disconnect: () => Promise<void>; sync: () => Promise<void>; reset: () => void; };
const Context = createContext<HybridContext | null>(null);

export function HybridERPProvider({ children }: { children: React.ReactNode }) {
  const [ledger, setLedger] = useState<HybridLedger>(emptyHybridLedger()); const [config, setConfig] = useState<GatewayConfig | null>(null); const [catalog, setCatalog] = useState<GatewayCatalog | null>(null); const [loading, setLoading] = useState(true); const [syncState, setSyncState] = useState<SyncState>("offline"); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { void (async () => { const [savedLedger, savedConfig] = await Promise.all([AsyncStorage.getItem(STORAGE_KEY), loadGatewayConfig()]); if (savedLedger) setLedger(JSON.parse(savedLedger) as HybridLedger); if (savedConfig) setConfig(savedConfig); setLoading(false); })(); }, []);
  const persist = useCallback((mapper: (current: HybridLedger) => HybridLedger) => setLedger((current) => { const next = { ...mapper(current), updatedAt: new Date().toISOString() }; void AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(next)); return next; }), []);
  const createCompany = useCallback((name: string, currency: string, country: string) => persist((current) => { const company = { id: makeId("company"), name, currency, country, createdAt: new Date().toISOString() }; return { ...current, company, outbox: [...current.outbox, queue("setup-company", { name, currency, country })] }; }), [persist]);
  const addCustomer = useCallback((name: string, email?: string) => persist((current) => { const customer = { id: makeId("customer"), name, email, createdAt: new Date().toISOString() }; return { ...current, customers: [...current.customers, customer], outbox: [...current.outbox, queue("add-customer", { name, email })] }; }), [persist]);
  const addItem = useCallback((sku: string, name: string, quantity: number, unitCost: number) => persist((current) => { const item = { id: makeId("item"), sku, name, quantity: amount(quantity), unitCost: amount(unitCost), createdAt: new Date().toISOString() }; return { ...current, items: [...current.items, item], outbox: [...current.outbox, queue("add-item", { sku, name, quantity: item.quantity, unit_cost: item.unitCost })] }; }), [persist]);
  const addInvoice = useCallback((quantity: number, unitPrice: number) => persist((current) => { const customer = current.customers[0]; const item = current.items[0]; if (!customer || !item) return current; const invoice = { id: makeId("invoice"), customerId: customer.id, itemId: item.id, quantity: amount(quantity), unitPrice: amount(unitPrice), status: "queued" as const, createdAt: new Date().toISOString() }; return { ...current, invoices: [...current.invoices, invoice], outbox: [...current.outbox, queue("create-sales-invoice", { customer_name: customer.name, item_code: item.sku, quantity: invoice.quantity, rate: invoice.unitPrice })] }; }), [persist]);
  const connect = useCallback(async (nextConfig: GatewayConfig) => { setSyncState("syncing"); setMessage(null); try { const [health, nextCatalog] = await Promise.all([checkGateway(nextConfig), getCatalog(nextConfig)]); await saveGatewayConfig(nextConfig); setConfig(nextConfig); setCatalog(nextCatalog); setSyncState(health.status === "ok" ? "ready" : "error"); setMessage(`${nextCatalog.total} remote actions are available when you sync.`); } catch (error) { setSyncState("error"); setMessage(error instanceof Error ? error.message : "Unable to contact the gateway."); throw error; } }, []);
  const disconnect = useCallback(async () => { await clearGatewayConfig(); setConfig(null); setCatalog(null); setSyncState("offline"); setMessage("Offline work remains safely on this device."); }, []);
  const sync = useCallback(async () => { if (!config) { setMessage("Add a gateway connection before syncing."); setSyncState("offline"); return; } setSyncState("syncing"); setMessage(null); const pending = ledger.outbox.filter((entry) => entry.status === "pending" || entry.status === "conflict"); let nextOutbox = [...ledger.outbox]; for (const entry of pending) { nextOutbox = nextOutbox.map((current) => current.id === entry.id ? { ...current, status: "syncing" } : current); try { await executeGatewayAction(config, entry.action, entry.args, true); nextOutbox = nextOutbox.map((current) => current.id === entry.id ? { ...current, status: "synced", message: undefined } : current); } catch (error) { const reason = error instanceof Error ? error.message : "Remote action failed."; nextOutbox = nextOutbox.map((current) => current.id === entry.id ? { ...current, status: "conflict", message: reason } : current); } } const hasConflict = nextOutbox.some((entry) => entry.status === "conflict"); const syncedInvoiceIds = new Set(nextOutbox.filter((entry) => entry.status === "synced" && entry.action === "create-sales-invoice").map((entry) => String(entry.args.item_code))); persist((current) => ({ ...current, outbox: nextOutbox, invoices: current.invoices.map((invoice) => syncedInvoiceIds.has(current.items.find((item) => item.id === invoice.itemId)?.sku ?? "") ? { ...invoice, status: "synced" } : invoice), lastSyncAt: new Date().toISOString() })); setSyncState(hasConflict ? "error" : "ready"); setMessage(hasConflict ? "Some actions need review before they can be retried." : "Local changes were sent to ERPClaw."); }, [config, ledger.outbox, persist]);
  const reset = useCallback(() => { const next = emptyHybridLedger(); setLedger(next); void AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(next)); }, []);
  const value = useMemo(() => ({ ledger, loading, config, catalog, syncState, message, createCompany, addCustomer, addItem, addInvoice, connect, disconnect, sync, reset }), [ledger, loading, config, catalog, syncState, message, createCompany, addCustomer, addItem, addInvoice, connect, disconnect, sync, reset]);
  return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useHybridERP() { const value = useContext(Context); if (!value) throw new Error("useHybridERP must be used inside HybridERPProvider."); return value; }
export function outboxStatus(outbox: OutboxAction[]) { return { pending: outbox.filter((entry) => entry.status === "pending").length, conflicts: outbox.filter((entry) => entry.status === "conflict").length, synced: outbox.filter((entry) => entry.status === "synced").length }; }
