import { useState } from "react";
import { Alert, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { AppButton, Card, StatusPill } from "@/components/erpclaw-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useERPClaw } from "@/contexts/erpclaw-context";

export default function ConnectScreen() {
  const router = useRouter(); const { connect, loading } = useERPClaw(); const [baseUrl, setBaseUrl] = useState(""); const [token, setToken] = useState(""); const [allowInsecureLocal, setAllowInsecureLocal] = useState(false);
  const handleConnect = async () => { try { await connect({ baseUrl, token: token.trim() || undefined, allowInsecureLocal }); router.replace("/(tabs)"); } catch (error) { Alert.alert("Connection failed", error instanceof Error ? error.message : "Could not connect to the ERPClaw gateway."); } };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-5"><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.hero}><StatusPill label="CLEAN FIRST RUN" tone="success" /><Text style={styles.title}>Connect your ERPClaw engine</Text><Text style={styles.subtitle}>This app starts empty. It will never create a company or load sample transactions until you explicitly complete setup.</Text></View><Card><Text style={styles.label}>Gateway address</Text><TextInput accessibilityLabel="ERPClaw gateway address" autoCapitalize="none" autoCorrect={false} keyboardType="url" onChangeText={setBaseUrl} placeholder="https://erpclaw.example.com" placeholderTextColor="#8A9690" style={styles.input} value={baseUrl} /><Text style={styles.help}>Use the HTTPS address of the self-hosted ERPClaw action gateway.</Text></Card><Card><Text style={styles.label}>Access token <Text style={styles.optional}>(optional)</Text></Text><TextInput accessibilityLabel="Gateway access token" autoCapitalize="none" autoCorrect={false} onChangeText={setToken} placeholder="Bearer token supplied by your gateway" placeholderTextColor="#8A9690" secureTextEntry style={styles.input} value={token} /><Text style={styles.help}>Stored with Android Keystore protection. It is never included in reports or receipts.</Text></Card><Card><View style={styles.switchRow}><View style={styles.switchCopy}><Text style={styles.label}>Private-network HTTP</Text><Text style={styles.help}>Enable only for a LAN development gateway. Public gateways must use HTTPS.</Text></View><Switch accessibilityLabel="Allow private-network HTTP" onValueChange={setAllowInsecureLocal} trackColor={{ false: "#CBD5D0", true: "#81BDB2" }} value={allowInsecureLocal} /></View></Card><AppButton disabled={loading || !baseUrl.trim()} icon="link" onPress={() => void handleConnect()} title={loading ? "Checking connection…" : "Connect securely"} /><Text style={styles.footnote}>A working Android client requires the companion gateway because the original ERPClaw engine is Python-based and remains the authoritative system of record.</Text></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingVertical: 28, gap: 16 }, hero: { gap: 10, marginBottom: 8 }, title: { color: "#17201E", fontSize: 30, fontWeight: "800", lineHeight: 36 }, subtitle: { color: "#64716C", fontSize: 16, lineHeight: 23 }, label: { color: "#17201E", fontSize: 15, fontWeight: "800" }, optional: { color: "#64716C", fontWeight: "500" }, input: { backgroundColor: "#F6F8F7", borderColor: "#D9E2DE", borderRadius: 12, borderWidth: 1, color: "#17201E", fontSize: 16, minHeight: 48, paddingHorizontal: 14 }, help: { color: "#64716C", fontSize: 13, lineHeight: 18 }, switchRow: { alignItems: "center", flexDirection: "row", gap: 16 }, switchCopy: { flex: 1, gap: 4 }, footnote: { color: "#64716C", fontSize: 13, lineHeight: 19, paddingHorizontal: 4, textAlign: "center" } });
