import { useState } from "react";
import { ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { AppButton, Card, StatusPill } from "@/components/erpclaw-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useHybridERP } from "@/contexts/hybrid-erp-context";
export default function HybridOnboarding() { const router = useRouter(); const { createCompany } = useHybridERP(); const [name, setName] = useState(""); const [currency, setCurrency] = useState("USD"); const [country, setCountry] = useState("US"); return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-5"><ScrollView contentContainerStyle={styles.content}><StatusPill label="OFFLINE FIRST" tone="success" /><Text style={styles.title}>Start now. Sync later.</Text><Text style={styles.copy}>Create your local business even without a server. The app queues a safe setup action for optional ERPClaw synchronization later.</Text><Card><Field label="Business name" value={name} onChange={setName} /><Field label="Currency" value={currency} onChange={setCurrency} /><Field label="Country" value={country} onChange={setCountry} /></Card><AppButton title="Create local company" icon="business" disabled={!name.trim()} onPress={() => { createCompany(name.trim(), currency.trim().toUpperCase(), country.trim().toUpperCase()); router.replace("/(tabs)" as never); }} /></ScrollView></ScreenContainer>; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChange} placeholderTextColor="#8A9690" style={styles.input} /></View>; }
const styles = StyleSheet.create({ content: { gap: 16, paddingVertical: 28 }, title: { color: "#17201E", fontSize: 29, fontWeight: "800" }, copy: { color: "#64716C", fontSize: 16, lineHeight: 23 }, field: { gap: 6 }, label: { color: "#17201E", fontSize: 14, fontWeight: "800" }, input: { backgroundColor: "#F6F8F7", borderColor: "#D9E2DE", borderRadius: 12, borderWidth: 1, color: "#17201E", minHeight: 48, paddingHorizontal: 14 } });
