import { useState } from "react";
import { Alert, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { AppButton, Card, StatusPill } from "@/components/erpclaw-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useERPClaw } from "@/contexts/erpclaw-context";

export default function OnboardingScreen() {
  const router = useRouter(); const { execute } = useERPClaw(); const [name, setName] = useState(""); const [abbr, setAbbr] = useState(""); const [currency, setCurrency] = useState("USD"); const [country, setCountry] = useState("US"); const [industry, setIndustry] = useState(""); const [confirmed, setConfirmed] = useState(false); const [submitting, setSubmitting] = useState(false);
  const createCompany = async () => { if (!confirmed) return; setSubmitting(true); try { const company = await execute("setup-company", { name: name.trim(), abbr: abbr.trim() || undefined, currency: currency.trim().toUpperCase(), country: country.trim().toUpperCase(), industry: industry.trim() || undefined }, true); const companyId = typeof company.company_id === "string" ? company.company_id : ""; if (!companyId) throw new Error("ERPClaw did not return the company identifier required for baseline setup."); await execute("seed-defaults", { company_id: companyId }, true); await execute("setup-chart-of-accounts", { company_id: companyId, template: "us_gaap" }, true); Alert.alert("Business setup complete", "Your company, baseline preferences, and US GAAP chart of accounts were created. No demo transactions were inserted.", [{ text: "Continue", onPress: () => router.replace("/(tabs)") }]); } catch (error) { Alert.alert("Business setup stopped", error instanceof Error ? error.message : "ERPClaw could not complete business setup."); } finally { setSubmitting(false); } };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-5"><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.hero}><StatusPill label="NO DEMO DATA" tone="success" /><Text style={styles.title}>Set up your real business</Text><Text style={styles.subtitle}>This one-time flow creates only the company and accounting foundation you choose. It does not add customers, stock, invoices, or sample balances.</Text></View><Card><Field label="Legal or trading name" value={name} onChangeText={setName} placeholder="Example: Acme Supply Co." /><Field label="Short name" value={abbr} onChangeText={setAbbr} placeholder="ACME" /><View style={styles.row}><View style={styles.half}><Field label="Currency" value={currency} onChangeText={setCurrency} placeholder="USD" maxLength={3} /></View><View style={styles.half}><Field label="Country" value={country} onChangeText={setCountry} placeholder="US" maxLength={2} /></View></View><Field label="Industry (optional)" value={industry} onChangeText={setIndustry} placeholder="retail, manufacturing, consulting…" /></Card><Card><View style={styles.confirmRow}><Switch accessibilityLabel="Confirm creation of company foundation" onValueChange={setConfirmed} trackColor={{ false: "#CBD5D0", true: "#81BDB2" }} value={confirmed} /><Text style={styles.confirmText}>I confirm that I want ERPClaw to create this company and its baseline accounting configuration.</Text></View></Card><AppButton disabled={!name.trim() || !confirmed || submitting} icon="business" onPress={() => void createCompany()} title={submitting ? "Creating foundation…" : "Create my company"} /></ScrollView></ScreenContainer>;
}
function Field({ label, value, onChangeText, placeholder, maxLength }: { label: string; value: string; onChangeText: (text: string) => void; placeholder: string; maxLength?: number }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput autoCapitalize={label === "Industry (optional)" ? "none" : "characters"} maxLength={maxLength} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#8A9690" style={styles.input} value={value} /></View>; }
const styles = StyleSheet.create({ content: { gap: 16, paddingVertical: 28 }, hero: { gap: 10 }, title: { color: "#17201E", fontSize: 29, fontWeight: "800", lineHeight: 35 }, subtitle: { color: "#64716C", fontSize: 16, lineHeight: 23 }, field: { gap: 7 }, label: { color: "#17201E", fontSize: 14, fontWeight: "800" }, input: { backgroundColor: "#F6F8F7", borderColor: "#D9E2DE", borderRadius: 12, borderWidth: 1, color: "#17201E", fontSize: 16, minHeight: 48, paddingHorizontal: 14 }, row: { flexDirection: "row", gap: 12 }, half: { flex: 1 }, confirmRow: { alignItems: "center", flexDirection: "row", gap: 12 }, confirmText: { color: "#3F4C46", flex: 1, fontSize: 14, lineHeight: 20 } });
