import { MaterialIcons } from "@expo/vector-icons";
import { ActivityIndicator, Pressable, StyleSheet, Text, View, type ViewStyle } from "react-native";

export function AppButton({ title, onPress, disabled, tone = "primary", icon }: { title: string; onPress: () => void; disabled?: boolean; tone?: "primary" | "secondary" | "danger"; icon?: keyof typeof MaterialIcons.glyphMap }) {
  return <Pressable accessibilityRole="button" accessibilityState={{ disabled }} disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.button, toneStyles[tone], disabled && styles.disabled, pressed && !disabled && styles.pressed]}>{icon ? <MaterialIcons color={tone === "secondary" ? "#0D5C5A" : "#FFFFFF"} name={icon} size={19} /> : null}<Text style={[styles.buttonText, tone === "secondary" && styles.secondaryText]}>{title}</Text></Pressable>;
}
export function StatusPill({ label, tone = "neutral" }: { label: string; tone?: "success" | "warning" | "error" | "neutral" }) { const colors = { success: ["#E3F6EB", "#177B50"], warning: ["#FFF2D8", "#865300"], error: ["#FCE5E7", "#B62D3A"], neutral: ["#EAF0ED", "#53605B"] } as const; return <View style={[styles.pill, { backgroundColor: colors[tone][0] }]}><Text style={{ color: colors[tone][1], fontSize: 12, fontWeight: "700" }}>{label}</Text></View>; }
export function LoadingBlock({ label = "Loading ERPClaw…" }: { label?: string }) { return <View style={styles.loading}><ActivityIndicator color="#0D5C5A" /><Text style={styles.loadingText}>{label}</Text></View>; }
export function Card({ children, style }: { children: React.ReactNode; style?: ViewStyle }) { return <View style={[styles.card, style]}>{children}</View>; }
const styles = StyleSheet.create({ button: { minHeight: 48, borderRadius: 14, paddingHorizontal: 18, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8 }, buttonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "800" }, secondaryText: { color: "#0D5C5A" }, pressed: { opacity: 0.82, transform: [{ scale: 0.98 }] }, disabled: { opacity: 0.5 }, card: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#D9E2DE", borderRadius: 18, padding: 16, gap: 10 }, pill: { alignSelf: "flex-start", borderRadius: 100, paddingHorizontal: 10, paddingVertical: 5 }, loading: { alignItems: "center", justifyContent: "center", gap: 12, paddingVertical: 40 }, loadingText: { color: "#64716C", fontSize: 15 } });
const toneStyles = StyleSheet.create({ primary: { backgroundColor: "#0D5C5A" }, secondary: { backgroundColor: "#EDF6F3", borderWidth: 1, borderColor: "#C5DDD6" }, danger: { backgroundColor: "#B62D3A" } });
