import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { actionDomain, actionSafety, humanizeAction } from "@/lib/erpclaw/action-safety";
import { LoadingBlock, StatusPill } from "@/components/erpclaw-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useERPClaw } from "@/contexts/erpclaw-context";
export default function ActionsScreen() { const router = useRouter(); const params = useLocalSearchParams<{ domain?: string }>(); const { catalog, loading } = useERPClaw(); const [query, setQuery] = useState(""); const domain = Array.isArray(params.domain) ? params.domain[0] : params.domain; const actions = useMemo(() => (catalog?.actions ?? []).filter((action) => (!domain || actionDomain(action) === domain) && (!query || action.includes(query.trim().toLowerCase()) || humanizeAction(action).toLowerCase().includes(query.trim().toLowerCase()))), [catalog?.actions, domain, query]); if (loading && !catalog) return <ScreenContainer><LoadingBlock label="Discovering ERPClaw actions…" /></ScreenContainer>; return <ScreenContainer className="px-5"><View style={styles.header}><Text style={styles.title}>{domain ? `${domain} actions` : "Action Center"}</Text><Text style={styles.subtitle}>{catalog ? `${catalog.total} engine actions available` : "Connect to discover the engine catalog"}</Text><TextInput accessibilityLabel="Search actions" autoCapitalize="none" autoCorrect={false} onChangeText={setQuery} placeholder="Search actions, e.g. sales invoice" placeholderTextColor="#8A9690" style={styles.search} value={query} /></View><FlatList contentContainerStyle={styles.list} data={actions} keyExtractor={(item) => item} ListEmptyComponent={<Text style={styles.empty}>No matching actions are available. Try a different search or reconnect to your gateway.</Text>} renderItem={({ item }) => { const safety = actionSafety(item); return <Pressable accessibilityRole="button" onPress={() => router.push(`/action/${item}` as never)} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><View style={styles.copy}><Text style={styles.rowTitle}>{humanizeAction(item)}</Text><Text style={styles.domain}>{actionDomain(item)}</Text></View><StatusPill label={safety === "read" ? "READ" : safety === "write" ? "WRITE" : "HIGH IMPACT"} tone={safety === "read" ? "neutral" : safety === "write" ? "warning" : "error"} /></Pressable>; }} /></ScreenContainer>; }
const styles = StyleSheet.create({ header: { gap: 7, paddingBottom: 12, paddingTop: 22 }, title: { color: "#17201E", fontSize: 28, fontWeight: "800" }, subtitle: { color: "#64716C", fontSize: 14 }, search: { backgroundColor: "#FFFFFF", borderColor: "#D9E2DE", borderRadius: 13, borderWidth: 1, color: "#17201E", fontSize: 16, minHeight: 48, paddingHorizontal: 14, marginTop: 6 }, list: { gap: 9, paddingBottom: 24 }, row: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#D9E2DE", borderRadius: 15, borderWidth: 1, flexDirection: "row", gap: 10, minHeight: 72, padding: 14 }, copy: { flex: 1, gap: 3 }, rowTitle: { color: "#17201E", fontSize: 16, fontWeight: "800" }, domain: { color: "#64716C", fontSize: 13 }, empty: { color: "#64716C", fontSize: 15, lineHeight: 21, paddingTop: 32, textAlign: "center" }, pressed: { opacity: 0.74 } });
