import { useEffect } from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { AppButton, Card, LoadingBlock, StatusPill } from "@/components/erpclaw-ui";
import { ScreenContainer } from "@/components/screen-container";
import { hybridSummary } from "@/lib/hybrid-erp";
import { useHybridERP } from "@/contexts/hybrid-erp-context";

export default function HomeScreen() { const router = useRouter(); const { ledger, loading, config, syncState } = useHybridERP(); const summary = hybridSummary(ledger); useEffect(() => { if (!loading && !ledger.company) router.replace("/hybrid-onboarding" as never); }, [ledger.company, loading, router]); if (loading) return <ScreenContainer><LoadingBlock label="Opening local workspace…" /></ScreenContainer>; if (!ledger.company) return null; return <ScreenContainer className="px-5"><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><View><Text style={styles.eyebrow}>HYBRID ERP</Text><Text style={styles.title}>{ledger.company.name}</Text></View><StatusPill label={syncState === "ready" ? "SYNC READY" : "OFFLINE"} tone={syncState === "ready" ? "success" : "warning"} /></View><Card><Text style={styles.cardTitle}>{config ? "Work offline. Sync when ready." : "Local first, no server required."}</Text><Text style={styles.body}>Changes stay on this phone until you choose to connect and sync them through ERPClaw.</Text></Card><View style={styles.stats}><Stat label="Queued" value={summary.pending} /><Stat label="Local customers" value={ledger.customers.length} /><Stat label="Local items" value={ledger.items.length} /></View><View style={styles.actions}><AppButton title="Work offline" icon="business-center" onPress={() => router.push("/(tabs)/work" as never)} /><AppButton title="Review sync outbox" icon="sync" tone="secondary" onPress={() => router.push("/(tabs)/sync" as never)} /><AppButton title={config ? "Edit gateway" : "Connect ERPClaw"} icon="link" tone="secondary" onPress={() => router.push("/hybrid-connect" as never)} /></View></ScrollView></ScreenContainer>; }
function Stat({ label, value }: { label: string; value: number }) { return <Card style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.body}>{label}</Text></Card>; }
const styles = StyleSheet.create({ content: { gap: 16, paddingVertical: 22 }, header: { alignItems: "flex-start", flexDirection: "row", justifyContent: "space-between", gap: 12 }, eyebrow: { color: "#0D5C5A", fontSize: 12, fontWeight: "800", letterSpacing: 1.2 }, title: { color: "#17201E", fontSize: 27, fontWeight: "800" }, cardTitle: { color: "#17201E", fontSize: 18, fontWeight: "800" }, body: { color: "#64716C", fontSize: 14, lineHeight: 20 }, stats: { flexDirection: "row", gap: 8 }, stat: { flex: 1, gap: 2, padding: 12 }, statValue: { color: "#17201E", fontSize: 22, fontWeight: "800" }, actions: { gap: 10 } });
