import { useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { actionDomain, actionSafety, humanizeAction } from "@/lib/erpclaw/action-safety";
import { AppButton, Card, StatusPill } from "@/components/erpclaw-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useERPClaw } from "@/contexts/erpclaw-context";

export default function ActionScreen() {
  const params = useLocalSearchParams<{ name: string; preset?: string }>(); const router = useRouter(); const { execute } = useERPClaw(); const action = Array.isArray(params.name) ? params.name[0] : params.name; const [input, setInput] = useState(params.preset ?? "{}"); const [submitting, setSubmitting] = useState(false); const safety = actionSafety(action);
  const run = async () => { let args: Record<string, unknown>; try { const parsed = JSON.parse(input || "{}"); if (!parsed || Array.isArray(parsed) || typeof parsed !== "object") throw new Error(); args = parsed as Record<string, unknown>; } catch { Alert.alert("Check the input", "Action inputs must be one JSON object, for example {\"company_id\": \"…\"}."); return; } const proceed = async () => { setSubmitting(true); try { const result = await execute(action, args, safety !== "read"); router.push({ pathname: "/result", params: { action, result: JSON.stringify(result) } } as never); } catch (error) { Alert.alert("Action did not complete", error instanceof Error ? error.message : "ERPClaw returned an unexpected response."); } finally { setSubmitting(false); } }; if (safety === "destructive") { Alert.alert("Confirm high-impact action", `This will run “${humanizeAction(action)}” against your real ERPClaw engine. Continue only if you understand the effect.`, [{ text: "Cancel", style: "cancel" }, { text: "Run action", style: "destructive", onPress: () => void proceed() }]); return; } if (safety === "write") { Alert.alert("Confirm business change", `ERPClaw will run “${humanizeAction(action)}” using the values below.`, [{ text: "Review", style: "cancel" }, { text: "Confirm", onPress: () => void proceed() }]); return; } await proceed(); };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-5"><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.header}><Text style={styles.eyebrow}>{actionDomain(action).toUpperCase()}</Text><Text style={styles.title}>{humanizeAction(action)}</Text><StatusPill label={safety === "read" ? "READ ONLY" : safety === "write" ? "CONFIRM TO RUN" : "HIGH IMPACT"} tone={safety === "read" ? "neutral" : safety === "write" ? "warning" : "error"} /></View><Card><Text style={styles.label}>Action inputs</Text><Text style={styles.help}>Enter arguments as a JSON object. This adaptive form exposes the full action catalog discovered from your connected ERPClaw engine.</Text><TextInput accessibilityLabel="Action JSON inputs" autoCapitalize="none" autoCorrect={false} multiline onChangeText={setInput} placeholder={'{\n  "company_id": "…"\n}'} placeholderTextColor="#8A9690" style={styles.jsonInput} textAlignVertical="top" value={input} /></Card><Card><Text style={styles.label}>Safety boundary</Text><Text style={styles.help}>{safety === "read" ? "This action is classified as read-only. ERPClaw still validates permissions and inputs on the engine." : safety === "write" ? "The application will show a final confirmation before it sends this business change to the engine." : "This high-impact action requires a second, explicit confirmation. The gateway also enforces engine-level consent rules."}</Text></Card><AppButton disabled={submitting} icon={safety === "read" ? "play-arrow" : "verified"} onPress={() => void run()} title={submitting ? "Running through ERPClaw…" : safety === "read" ? "Run read-only action" : "Review and run action"} tone={safety === "destructive" ? "danger" : "primary"} /></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { gap: 16, paddingVertical: 24 }, header: { gap: 8 }, eyebrow: { color: "#0D5C5A", fontSize: 12, fontWeight: "800", letterSpacing: 1 }, title: { color: "#17201E", fontSize: 28, fontWeight: "800", lineHeight: 34 }, label: { color: "#17201E", fontSize: 15, fontWeight: "800" }, help: { color: "#64716C", fontSize: 14, lineHeight: 20 }, jsonInput: { backgroundColor: "#10211D", borderRadius: 12, color: "#E7F0ED", fontFamily: "monospace", fontSize: 14, lineHeight: 20, minHeight: 210, padding: 14 } });
